// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY3ZAzMTf1czntQkMjv8o06F4kVl4LId0',
    appId: '1:1084694881314:web:ff3873d4b0efd3dfb6167b',
    messagingSenderId: '1084694881314',
    projectId: 'thinkwin-d3a6a',
    authDomain: 'thinkwin-d3a6a.firebaseapp.com',
    storageBucket: 'thinkwin-d3a6a.firebasestorage.app',
    measurementId: 'G-X0KF0KT4XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAydmH4Lw2NrZQxKVJcsmR8q9fISGFstrQ',
    appId: '1:1084694881314:android:907cb5afc8d1fed6b6167b',
    messagingSenderId: '1084694881314',
    projectId: 'thinkwin-d3a6a',
    storageBucket: 'thinkwin-d3a6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSwWM0d-_4uxMQmgopj3sfQb2N5XoTpzY',
    appId: '1:1084694881314:ios:a283c963bfe5ff40b6167b',
    messagingSenderId: '1084694881314',
    projectId: 'thinkwin-d3a6a',
    storageBucket: 'thinkwin-d3a6a.firebasestorage.app',
    iosBundleId: 'com.devtestify.thinkwin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSwWM0d-_4uxMQmgopj3sfQb2N5XoTpzY',
    appId: '1:1084694881314:ios:a283c963bfe5ff40b6167b',
    messagingSenderId: '1084694881314',
    projectId: 'thinkwin-d3a6a',
    storageBucket: 'thinkwin-d3a6a.firebasestorage.app',
    iosBundleId: 'com.devtestify.thinkwin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY3ZAzMTf1czntQkMjv8o06F4kVl4LId0',
    appId: '1:1084694881314:web:f32eddc38a1aed15b6167b',
    messagingSenderId: '1084694881314',
    projectId: 'thinkwin-d3a6a',
    authDomain: 'thinkwin-d3a6a.firebaseapp.com',
    storageBucket: 'thinkwin-d3a6a.firebasestorage.app',
    measurementId: 'G-WF14TN45P0',
  );
}
